### ISSUE TITLE
Major Revamp

### ISSUE THREAD

**Issue by trihargianto** [trihargianto/apparel-customizer#32]
The code on this repository was written 6 years ago & I need to rewrite the code to be more clean and maintainable. 

## Todo

- [x] #33
- [x] #35
- [x] #37
- [x] #39
- [x] #41
- [ ] Improve existing and add new features
    - [x] #45
    - [ ]  Able to **flip front and back** for the apparel
    - [x] #48
    - [x] #46
    - [x]  Add assets
        - [x] #50
        - [x]  Add image
            - [x] #68
            - [x] #51
        - [x] #53
    - [x] #55
    - [x] #56
    - [x] #58
    - [ ] #61
    - [ ]  Undo redo feature
    - [ ]  Keyboard shortcut feature
    - [x] #65
- [ ]  Web Performance Improvement
- [ ] Support offline mode 
- [ ] Installable to the user devices 
- [ ] Support Dark Mode
- [x]  Support mobile screen
